import type { ProgramWorld } from "./types";

export const PROGRAM_WORLDS: ProgramWorld[] = [
  {
    id: "w1",
    n: 1,
    title: "一个按钮活起来",
    blurb: "template / ref / .value / computed / watch",
    status: "ready",
    labIds: ["ref", "computed", "watch"],
    topics: ["ref", "computed", "watch", ".value"],
  },
  {
    id: "w2",
    n: 2,
    title: "Todo 从 20 行长到 150 行",
    blurb: "list / form / component / props / emit / slots",
    status: "ready",
    labIds: ["list", "form", "component", "slots"],
    topics: ["list", "form", "component", "props", "emit", "slots"],
  },
  {
    id: "w3",
    n: 3,
    title: "Todo 成为真正 SPA",
    blurb: "composables / pinia / router",
    status: "ready",
    labIds: ["composable", "pinia", "router"],
    topics: ["composables", "pinia", "router"],
  },
  {
    id: "w4",
    n: 4,
    title: "接入现实世界",
    blurb: "fetch / loading / error / race / crud / auth",
    status: "ready",
    labIds: ["fetch", "error", "race", "crud", "auth"],
    topics: ["fetch", "loading", "error", "race", "crud", "auth"],
  },
  {
    id: "w5",
    n: 5,
    title: "应用开始复杂",
    blurb: "provide / inject / keep-alive / teleport / transition",
    status: "ready",
    labIds: ["provide", "keepalive", "teleport", "transition"],
    topics: ["provide", "inject", "keep-alive", "teleport", "transition"],
  },
  {
    id: "w6",
    n: 6,
    title: "应用坏掉",
    blurb: "debugging / DevTools / testing",
    status: "soon",
    labIds: [],
    topics: ["debug", "testing"],
  },
  {
    id: "w7",
    n: 7,
    title: "生产环境",
    blurb: "build / SSR / Nuxt / deployment",
    status: "soon",
    labIds: [],
    topics: ["ssr", "nuxt", "deploy"],
  },
];
