import type { ProgramWorld } from "./types";

export const PROGRAM_WORLDS: ProgramWorld[] = [
  {
    id: "w1",
    n: 1,
    title: "一个按钮活起来",
    blurb: "template / ref / .value / computed / watch",
    status: "ready",
    labIds: ["ref", "computed", "watch"],
    topics: ["ref", "computed", "watch", ".value"],
  },
  {
    id: "w2",
    n: 2,
    title: "Todo 从 20 行长到 150 行",
    blurb: "list / form / component / props / emit / slots",
    status: "ready",
    labIds: ["list", "form", "component", "slots"],
    topics: ["list", "form", "component", "props", "emit", "slots"],
  },
  {
    id: "w3",
    n: 3,
    title: "Todo 成为真正 SPA",
    blurb: "composables / pinia / router",
    status: "ready",
    labIds: ["composable", "pinia", "router"],
    topics: ["composables", "pinia", "router"],
  },
  {
    id: "w4",
    n: 4,
    title: "接入现实世界",
    blurb: "fetch / loading / error / race / crud / auth",
    status: "ready",
    labIds: ["fetch", "error", "race", "crud", "auth"],
    topics: ["fetch", "loading", "error", "race", "crud", "auth"],
  },
  {
    id: "w5",
    n: 5,
    title: "应用开始复杂",
    blurb: "provide / inject / keep-alive / teleport / transition",
    status: "ready",
    labIds: ["provide", "keepalive", "teleport", "transition"],
    topics: ["provide", "inject", "keep-alive", "teleport", "transition"],
  },
  {
    id: "w6",
    n: 6,
    title: "应用坏掉",
    blurb: "nextTick / onErrorCaptured / testing",
    status: "ready",
    labIds: ["nexttick", "capture", "test"],
    topics: ["nextTick", "onErrorCaptured", "testing"],
  },
  {
    id: "w7",
    n: 7,
    title: "生产环境",
    blurb: "hydrate / isolate / payload",
    status: "ready",
    labIds: ["hydrate", "isolate", "payload"],
    topics: ["hydrate", "isolate", "payload"],
  },
  {
    id: "w8",
    n: 8,
    title: "类型",
    blurb: "defineProps / defineEmits / InjectionKey",
    status: "ready",
    labIds: ["typedprops", "typedemit", "injectkey"],
    topics: ["defineProps", "defineEmits", "InjectionKey"],
  },
  {
    id: "w9",
    n: 9,
    title: "组件上的双向门",
    blurb: "defineModel / 修饰符 / 具名 v-model",
    status: "ready",
    labIds: ["definemodel", "modelmod", "multimodel"],
    topics: ["defineModel", "v-model.trim", "v-model:title"],
  },
  {
    id: "w10",
    n: 10,
    title: "追踪停在哪一层",
    blurb: "shallowRef / markRaw / customRef",
    status: "ready",
    labIds: ["shallow", "markraw", "customref"],
    topics: ["shallowRef", "markRaw", "customRef"],
  },
  {
    id: "w11",
    n: 11,
    title: "贴到哪一层，开哪一扇窗",
    blurb: "$attrs / inheritAttrs / defineExpose",
    status: "ready",
    labIds: ["attrs", "inherit", "expose"],
    topics: ["$attrs", "inheritAttrs", "defineExpose"],
  },
  {
    id: "w12",
    n: 12,
    title: "指令碰到了 DOM",
    blurb: "v-focus / 参数与修饰符 / 卸掉时摘监听",
    status: "ready",
    labIds: ["vfocus", "vpaint", "vclickout"],
    topics: ["v-focus", "binding.arg", "unmounted"],
  },
  {
    id: "w13",
    n: 13,
    title: "还没到的组件",
    blurb: "defineAsyncComponent / Suspense / retry",
    status: "ready",
    labIds: ["asynccomp", "suspense", "asyncerr"],
    topics: ["defineAsyncComponent", "Suspense", "retry"],
  },
  {
    id: "w14",
    n: 14,
    title: "样式也有边界",
    blurb: "scoped / :deep / :slotted",
    status: "ready",
    labIds: ["scoped", "deep", "slotted"],
    topics: ["scoped", ":deep", ":slotted"],
  },
  {
    id: "w15",
    n: 15,
    title: "安装才接通",
    blurb: "app.use / 全局组件 / options",
    status: "ready",
    labIds: ["plugin", "globcomp", "plugopt"],
    topics: ["app.use", "app.component", "options"],
  },
  {
    id: "w16",
    n: 16,
    title: "有些节点不必再画",
    blurb: "v-once / v-memo / 列表上的名单",
    status: "ready",
    labIds: ["vonce", "vmemo", "vmemolist"],
    topics: ["v-once", "v-memo", "v-for"],
  },
];
