/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CausalRouteImport } from './routes/causal'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as CheatsheetRouteImport } from './routes/cheatsheet'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CausalIndexRouteImport } from './routes/causal.index'
import { Route as CausalLabIdRouteImport } from './routes/causal.$labId'
import { Route as LessonSlugRouteImport } from './routes/lesson.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CausalRoute = CausalRouteImport.update({
  id: '/causal',
  path: '/causal',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetRoute = CheatsheetRouteImport.update({
  id: '/cheatsheet',
  path: '/cheatsheet',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CausalIndexRoute = CausalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CausalRoute,
} as any)
const CausalLabIdRoute = CausalLabIdRouteImport.update({
  id: '/$labId',
  path: '/$labId',
  getParentRoute: () => CausalRoute,
} as any)
const LessonSlugRoute = LessonSlugRouteImport.update({
  id: '/lesson/$slug',
  path: '/lesson/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/causal': typeof CausalRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/docs': typeof DocsRoute
  '/hub': typeof HubRoute
  '/lab': typeof LabRoute
  '/mistakes': typeof MistakesRoute
  '/playground': typeof PlaygroundRoute
  '/studio': typeof StudioRoute
  '/causal/$labId': typeof CausalLabIdRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/causal/': typeof CausalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/docs': typeof DocsRoute
  '/hub': typeof HubRoute
  '/lab': typeof LabRoute
  '/mistakes': typeof MistakesRoute
  '/playground': typeof PlaygroundRoute
  '/studio': typeof StudioRoute
  '/causal/$labId': typeof CausalLabIdRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/causal': typeof CausalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/causal': typeof CausalRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/cheatsheet': typeof CheatsheetRoute
  '/docs': typeof DocsRoute
  '/hub': typeof HubRoute
  '/lab': typeof LabRoute
  '/mistakes': typeof MistakesRoute
  '/playground': typeof PlaygroundRoute
  '/studio': typeof StudioRoute
  '/causal/$labId': typeof CausalLabIdRoute
  '/lesson/$slug': typeof LessonSlugRoute
  '/causal/': typeof CausalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/causal'
    | '/certificate'
    | '/cheatsheet'
    | '/docs'
    | '/hub'
    | '/lab'
    | '/mistakes'
    | '/playground'
    | '/studio'
    | '/causal/$labId'
    | '/lesson/$slug'
    | '/causal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/cheatsheet'
    | '/docs'
    | '/hub'
    | '/lab'
    | '/mistakes'
    | '/playground'
    | '/studio'
    | '/causal/$labId'
    | '/lesson/$slug'
    | '/causal'
  id:
    | '__root__'
    | '/'
    | '/causal'
    | '/certificate'
    | '/cheatsheet'
    | '/docs'
    | '/hub'
    | '/lab'
    | '/mistakes'
    | '/playground'
    | '/studio'
    | '/causal/$labId'
    | '/lesson/$slug'
    | '/causal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CausalRoute: typeof CausalRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  CheatsheetRoute: typeof CheatsheetRoute
  DocsRoute: typeof DocsRoute
  HubRoute: typeof HubRoute
  LabRoute: typeof LabRoute
  MistakesRoute: typeof MistakesRoute
  PlaygroundRoute: typeof PlaygroundRoute
  StudioRoute: typeof StudioRoute
  LessonSlugRoute: typeof LessonSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causal': {
      id: '/causal'
      path: '/causal'
      fullPath: '/causal'
      preLoaderRoute: typeof CausalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheet': {
      id: '/cheatsheet'
      path: '/cheatsheet'
      fullPath: '/cheatsheet'
      preLoaderRoute: typeof CheatsheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causal/': {
      id: '/causal/'
      path: '/'
      fullPath: '/causal/'
      preLoaderRoute: typeof CausalIndexRouteImport
      parentRoute: typeof CausalRoute
    }
    '/causal/$labId': {
      id: '/causal/$labId'
      path: '/$labId'
      fullPath: '/causal/$labId'
      preLoaderRoute: typeof CausalLabIdRouteImport
      parentRoute: typeof CausalRoute
    }
    '/lesson/$slug': {
      id: '/lesson/$slug'
      path: '/lesson/$slug'
      fullPath: '/lesson/$slug'
      preLoaderRoute: typeof LessonSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CausalRouteChildren {
  CausalLabIdRoute: typeof CausalLabIdRoute
  CausalIndexRoute: typeof CausalIndexRoute
}

const CausalRouteChildren: CausalRouteChildren = {
  CausalLabIdRoute: CausalLabIdRoute,
  CausalIndexRoute: CausalIndexRoute,
}

const CausalRouteWithChildren =
  CausalRoute._addFileChildren(CausalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CausalRoute: CausalRouteWithChildren,
  CertificateRoute: CertificateRoute,
  CheatsheetRoute: CheatsheetRoute,
  DocsRoute: DocsRoute,
  HubRoute: HubRoute,
  LabRoute: LabRoute,
  MistakesRoute: MistakesRoute,
  PlaygroundRoute: PlaygroundRoute,
  StudioRoute: StudioRoute,
  LessonSlugRoute: LessonSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
